
name: My First Pipeline

on:
  push:

jobs:
  hello-job:

    runs-on: ubuntu-latest

    steps:

      - name: Print Welcome Message
        run: echo "Welcome to GitHub Actions"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls
