name: my Second Pipeline

on:
  push:

jobs:
  demo-job:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: show current directory
        run: pwd

      - name: Show Repository Directory
        run: ls -la

      - name: System Information

        run: |

         pwd

         ls -la

         whoami

         uname -a

         date
